name: CICD for Nesto-Backend

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build

        env: 
          CI: true   


  depoly:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.HOST }}
          username:  ec2-user
          key:  ${{ secrets.KEY }}
          port:  ${{ secrets.PORT }}
          script: |
               cd ..
               cd ..
               cd NestoHub-Backend/
               git stash
               git pull origin main
               npm install
               npm run build
               pm2 restart api
            



